# Generated by Django 4.2.1 on 2023-05-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_address_customers_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='order',
            field=models.TextField(blank=True, null=True),
        ),
    ]
