# Generated by Django 4.2.1 on 2023-05-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customeraddress_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAdhaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhaar_number', models.IntegerField(blank=True, null=True)),
                ('adhaar_name', models.CharField(blank=True, max_length=15, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customers')),
            ],
        ),
    ]
