# Generated by Django 4.2.1 on 2023-05-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customeradhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeradhaar',
            name='adhaar_name',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
